spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/aisa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false

server:
  port: 8081
